//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoSoDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        public int Id { get; set; }
        public string Nmae { get; set; }
        public Nullable<int> Episode { get; set; }
        public Nullable<int> Rating { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> isWatch { get; set; }
        public string AnimeImg { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
